trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '/src/*.sln'
    arguments: '--configuration $(buildConfiguration)'
  


